#!/bin/bash

names=("adam" "ruth" "hagar" "eve" "solomon" "david" "abraham" "moses")

for i in {1..10}; do
    random_id=$RANDOM
    random_index=$((RANDOM % 8))
    random_name=${names[random_index]}
    echo "insert $random_id $random_name $random_name@gmail" >> input.txt
done

