enum StatementType {
    SELECT,
    INSERT
};

enum PrepareResult {
    PREPARE_SUCCESS,
    PREPARE_ARGUMENT_SIZE_FAIL,
    PREPARE_NEGATIVE_ID,
    PREPARE_STRING_TOO_LONG,
    PREPARE_UNRECOGNIZED_STATEMENT
};

enum ExecuteResult {
    EXECUTE_SUCCESS,
    EXECUTE_FAILURE,
    EXECUTE_TABLE_FULL
};
