#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TABLE_MAX_PAGES 100
#define PAGE_MAX_SIZE 4096
#define EMAIL_MAX_SIZE 255
#define USERNAME_MAX_SIZE 32
#define ROW_MAX_SIZE 319
#define ROWS_PER_PAGE 12

#endif
